### PR TITLE
Fixes #17094: Move keepalive settings from katello to foreman

### PR DESCRIPTION
**Pull request by ekohl**
https://github.com/Katello/puppet-katello/pull/141

### CODE REVIEW

**Comment by ekohl** [comment]
Verified it works by creating a fresh centos7-katello-p4-nightly, provision it, manually apply the patches (which is harder that it should be IMHO) and rerun the provision step.

**Comment by stbenjam** [comment]
@ekohl There's a rubocop warning on your code, 10000 should be `10_000` or feel free to disable the check

**Comment by ekohl** [comment]
Rebased and fixed the rubocop. Should I create a redmine issue as well?

**Comment by stbenjam** [comment]
@ekohl Oh yes please, we enforce it for this repo

**Comment by ekohl** [comment]
Now with a redmine issue

**Comment by stbenjam** [comment]
Thanks @ekohl !

**Pull request merged**
