### PR TITLE
Fixes #13546 - Enable TFTP during install

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
References this one https://github.com/Katello/katello-installer/pull/377

**Comment by stbenjam** [comment]
Thanks, with this change, tftp is on by default with the katello scenario.  Do we need this on capsules too? https://github.com/Katello/katello-installer/blob/master/config/capsule.migrations/160120212700-foreman-proxy.rb#L34

**Comment by chris1984** [comment]
@stbenjam thanks for catching that, updated with the capsule migration as well.

**Comment by stbenjam** [comment]
Thanks @chris1984!

**Pull request merged**
