### PR TITLE
Fixes #9834 - Ensure plugin settings directory exists for gutterball (ka...

### PR DESCRIPTION
**Pull request by dustints**
...tello_devel)

### CODE REVIEW

**Comment by thomasmckay** [comment]
ACK from testing katello-deploy dev install

**Comment by ehelms** [comment]
This pulls in a lot of changes that are currently in other PRs to the installer. I would prefer those are merged first and this PR rebased before it is merged.

**Comment by thomasmckay** [comment]
ack again from testing w/ PR 196

**Comment by ehelms** [comment]
Can you rebase this now that #190 has been merged?

**Comment by dustints** [comment]
updated...`librarian-puppet update katello-katello_devel` still pulling in updates for postgresql and mongodb, katello-certs

**Comment by ehelms** [comment]
APJ

**Comment by dustints** [comment]
@ehelms lets go with https://github.com/Katello/katello-installer/pull/198 first then...it's green opposed to this one.

**Comment by jlsherrill** [comment]
[test]

**Comment by dustints** [comment]
[test]

**Comment by dustints** [comment]
rebased

**Pull request merged**
