### PR TITLE
Refs #20879 - split oauth for Pulp & Candlepin

### PR DESCRIPTION
**Pull request by sean797**

### CODE REVIEW

**Comment by ekohl** [comment]
You need some check to see if they exist. How about moving these keys to candlepin? Then you won't have to restart candlepin while you need to restart Apache anyway.

**Comment by ehelms** [comment]
Can you give some more details on this? We are just straight clearing existing oauth for users on upgrade?

**Comment by sean797** [comment]
Updated. It now moves them to `candlepin_*` if they exist. Ready for the above linked puppet PR.

**Comment by ekohl** [comment]
[split candlepin/pulp oauth](https://trello.com/c/afmNVNIX/513-split-candlepin-pulp-oauth)

**Comment by sean797** [comment]
@ekohl I get 

```
This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams.
```

Can you invite me or make it public ?

**Comment by ekohl** [comment]
@sean797 that card was from our teams internal board. It wasn't all that interesting, just a link that this PR should get attention. We did an experiment to better integrate with Github but it didn't quite do what we expected. While it did nicely show the build status and labels, the UI to add them wasn't all that good and on top of that it posted the link to the issue.

**Pull request closed without merging**
