### PR TITLE
Fixes #9715: Lock pulp module to 0.1.0 line.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
APJ

**Comment by domcleal** [comment]
Please double check your issue number: http://projects.theforeman.org/issues/9175#change-39088

**Comment by ehelms** [comment]
@domcleal thanks for the catch, this is not my week for getting numbers properly ordered

**Comment by domcleal** [comment]
@ehelms thanks, you may want to change the PR title too as the bot reads from that, IIRC

**Pull request merged**
