### PR TITLE
Fixes #14098 - Removed steps to register

### PR DESCRIPTION
**Pull request by chris1984**
Removed steps to register capsule since it would be registered already.

### CODE REVIEW

**Comment by ehelms** [comment]
Why would it be registered already? You could argue registration is no longer required with the host unification changes @jlsherrill correct if I am misspeaking.

**Comment by chris1984** [comment]
@ehelms I based the pr off of this downstream BZ https://bugzilla.redhat.com/show_bug.cgi?id=1194162

**Comment by ehelms** [comment]
I like his suggestion in the bug, mentioning to the user the need to register if they have not already registered to the Satellite or want to manage the Capsule's content and errata. Perhaps just the former to impress best practices to the user.

**Comment by chris1984** [comment]
@ehelms Ack, I will fix my commit and update the wording on the steps I took out.

**Comment by beav** [comment]
change looks good to me, ACK

**Comment by chris1984** [comment]
@ehelms does this look good for a merge

**Comment by ehelms** [comment]
Thanks @chris1984 !

**Pull request merged**
