### PR TITLE
Fixes #13908 - use prefixed options in capsule and katello-devel

### PR DESCRIPTION
**Pull request by mbacovsky**

### CODE REVIEW

**Comment by bbuckingham** [comment]
The changes pass the 'eyeball' test.  I'll run a test of installing katello, capsule and katello-devel to ensure all is well there too.

**Comment by bbuckingham** [comment]
The installer succeeds via katello-deploy for 'centos7-katello-devel'; however, it failed for 'centos7-katello'.  The behavior that i see is below.  Do you happen to see the same on your config?

```
==> centos7-katello-nightly: Complete!
==> centos7-katello-nightly: /vagrant/lib/katello_deploy/installer.rb:102:in `symlink': File exists - (/vagrant/katello-installer/config/katello.yaml, katello.yaml) (Errno::EEXIST)
==> centos7-katello-nightly: 	from /vagrant/lib/katello_deploy/installer.rb:102:in `symlink'
==> centos7-katello-nightly: 	from /vagrant/lib/katello_deploy/installer.rb:46:in `block in setup_config'
==> centos7-katello-nightly: 	from /vagrant/lib/katello_deploy/installer.rb:45:in `chdir'
==> centos7-katello-nightly: 	from /vagrant/lib/katello_deploy/installer.rb:45:in `setup_config'
==> centos7-katello-nightly: 	from /vagrant/lib/katello_deploy/installer.rb:22:in `install'
==> centos7-katello-nightly: 	from ./setup.rb:115:in `<main>'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by bbuckingham** [comment]
ACK

**Comment by ehelms** [comment]
Thanks @mbacovsky !

**Pull request merged**
