### PR TITLE
Fixes #21433 - Only reset foreman params on server during P4 upgrade

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by chris1984** [comment]
@ehelms is there a way to check this only reset the foreman params when running --reset?

**Comment by ehelms** [comment]
@chris1984 note this is just Puppet 4 upgrade to consider when testing, on a proxy today, the error is:

```

Upgrade Step: start_httpd...
/usr/sbin/service-wait httpd start
Redirecting to /bin/systemctl start httpd.service

Success!
katello-service start --only httpd finished successfully!
Puppet 3 to 4 upgrade initialization complete, continuing with installation
Resetting puppet params...
/usr/share/katello-installer-base/hooks/boot/01-helpers.rb:59:in `reset_value': undefined method `unset_value' for nil:NilClass (NoMethodError)
	from /usr/share/katello-installer-base/hooks/pre_validations/31-upgrade-puppet.rb:19:in `block (4 levels) in load'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/hooking.rb:34:in `instance_eval'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/hooking.rb:34:in `block (4 levels) in load'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/hook_context.rb:15:in `instance_exec'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/hook_context.rb:15:in `execute'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/hooking.rb:51:in `block in execute'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/hooking.rb:49:in `each'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/hooking.rb:49:in `execute'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/kafo_configure.rb:140:in `execute'
	from /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/kafo_configure.rb:119:in `run'
	from /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
	from /usr/share/gems/gems/kafo-2.0.0/lib/kafo/kafo_configure.rb:163:in `run'
	from /usr/sbin/satellite-installer:8:in `<main>'
```

**Comment by ehelms** [comment]
I can't find a good way to shorten the commit message without making it lose meaning.

**Comment by chris1984** [comment]
Works:

Katello:

~~~
Puppet 3 to 4 upgrade param reset, continuing with installation
Installing             Done                                               [100%] [.......................................................................................................................................................................................................]
  Success!
  * Katello is running at https://katello.test.lan
  * To install an additional Foreman proxy on separate machine continue by running:

      foreman-proxy-certs-generate --foreman-proxy-fqdn "$FOREMAN_PROXY" --certs-tar "/root/$FOREMAN_PROXY-certs.tar"
  The full log is at /var/log/foreman-installer/katello.log
Upgrade Step: restart_services...
~~~~

Proxy:

~~~
Puppet 3 to 4 upgrade param reset, continuing with installation
Installing             Done                                               [100%] [.......................................................................................................................................................................................................]
  Success!
  * Foreman Proxy is running at https://cap.test.lan:9090
  The full log is at /var/log/foreman-installer/foreman-proxy-content.log
Upgrade Step: restart_services...
~~~

**Comment by chris1984** [comment]
Thanks @ehelms

**Pull request merged**
