### PR TITLE
Fixes 8609 - validate the custom certificates passed in arguments on the installer

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by iNecas** [comment]
So the question is: rewrite or not? The facts are there. I'm not going to argue anymore: resolving this issue is more important to me than the language it's written in (although you know my preference:)

**Comment by ehelms** [comment]
My preference hasn't been swayed either. I guess we let @jlsherrill break the tie and blame him there after ;)

**Comment by jlsherrill** [comment]
eh, at this point I'm okay with it.  I'd prefer ruby, but i'm okay with bash.  The script isn't *that* complex.

**Comment by mccun934** [comment]
can we get a rebase and merge as the tie has been broken

**Comment by iNecas** [comment]
Rebased

**Comment by ehelms** [comment]
@iNecas Looks like you you hit an RPM build failure.

**Comment by iNecas** [comment]
right, updated

**Comment by ehelms** [comment]
ACK

**Pull request merged**
