### PR TITLE
Pin modules to releases on the forge

### PR DESCRIPTION
**Pull request by stbenjam**
@ehelms  What do you think about trying to adopt the Foreman model of only using released modules?

Every release foreman does this pinning, see the stable branch: https://github.com/theforeman/foreman-installer/blob/1.9-stable/Puppetfile

1 - This ensures Katello 2.3 installs using the some modules as Foreman 1.9, instead of from git
2 - We can start introducing a release process for katello's modules

I'd go ahead and release a version of each of our modules, too, and pin the 2.3 release to them.

### CODE REVIEW

**Comment by ehelms** [comment]
I think that is a sound strategy, especially if we get in the habit of releasing modules more. I assume not all modules would be released at 1.X due to their potential lack of stability?

**Comment by stbenjam** [comment]
Yea, so my game plan is to make very minimal modifications to the modules, to clean up their dependencies (remove unnecessary, make version pinning consistent), and then in most cases release the version in metadata.json now (most likely 0.1.0).

So far:

* [ ] https://github.com/Katello/puppet-candlepin/pull/22
* [ ] https://github.com/Katello/puppet-certs/pull/63
* [ ] https://github.com/Katello/puppet-capsule/pull/51
* [ ] https://github.com/Katello/puppet-common/pull/4
* [ ] https://github.com/Katello/puppet-elasticsearch/pull/6
* [ ] https://github.com/Katello/puppet-gutterball/pull/12

**Comment by stbenjam** [comment]
Last ones:

* [ ] https://github.com/Katello/puppet-katello/pull/72
* [ ] https://github.com/Katello/puppet-crane/pull/5
* [ ] https://github.com/Katello/puppet-service_wait/pull/10
* [ ] https://github.com/Katello/puppet-pulp/pull/88

**Comment by stbenjam** [comment]
Ok, pinned.  `librarian-puppet install` worked without issues.  Let's see what happens!

omg-excited

**Comment by stbenjam** [comment]
Green! :green_heart:

**Comment by ehelms** [comment]
ACK

**Comment by stbenjam** [comment]
Thanks @ehelms!

**Pull request merged**
