### PR TITLE
Fixes #9964 - katello-installer should use apipie:cache:index

### PR DESCRIPTION
**Pull request by bagasse**

### CODE REVIEW

**Comment by ehelms** [comment]
Please see -- https://github.com/Katello/katello-installer#filing-and-fixing-issues

**Comment by bagasse** [comment]
> We have puppet-foreman locked to a particular version

Sorry, I missed that point.

**Comment by ehelms** [comment]
@bagasse we've had to lock those modules due to the fact that the latest versions of puppetlabs-apache end up causing our installer to segfault on 1.8.7

**Comment by ehelms** [comment]
We've recently updated the modules and this is now handled, see https://github.com/Katello/katello-installer/blob/master/modules/foreman/manifests/database.pp#L39

**Pull request closed without merging**
