### PR TITLE
Module update.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
[test]

**Comment by ehelms** [comment]
@stbenjam or @jlsherrill  are you OK with doing a mass module update like this?

**Comment by stbenjam** [comment]
Fine for me, BATS is green. 

I was looking at foreman-installer the other day and I do wish we'd move to that model - not now, but in the medium-term (2.4?).

**Comment by ehelms** [comment]
I would prefer that as well, however, I don't know what the scenario installer will mean so that is partially why I have avoided it.

**Pull request merged**
