### PR TITLE
Fixes #22905 - Remove katello_devel and devel scenarios

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ekohl** [comment]
I realized this breaks because we depend on the puppetlabs-vcsrepo module. We need some way to get this dependency.

**Comment by ehelms** [comment]
We need it for the puppet-katello_devel in the new Forklift work or we need it for modules that aren't puppet-katello_devel ?

**Comment by ekohl** [comment]
I believe it's only required by the devel module if you remove it here, you need to install it in forklift

**Comment by ehelms** [comment]
Fix here -- https://github.com/theforeman/forklift/pull/659

**Comment by ehelms** [comment]
@ekohl Given https://github.com/theforeman/forklift/pull/659 is merged, can you re-review?

**Pull request merged**
