### PR TITLE
Fixes #9466 - gutterball.conf missing gutterball.amqp.connect

### PR DESCRIPTION
**Pull request by dustints**
librarian-puppet update katello-katello katello-gutterball

### CODE REVIEW

**Comment by dustints** [comment]
seeing # [ERROR 2015-02-19 22:32:32 verbose]  katello-centos6-bats: This module does not support osfamily CentOS at /vagrant/katello-installer/modules/pulp/manifests/params.pp:55 on node katello-centos6-bats.example.com

**Comment by dustints** [comment]
^ fixed by https://github.com/Katello/puppet-pulp/pull/39

**Comment by dustints** [comment]
```
# Debug: /Stage[main]/Certs::Foreman/Exec[foreman_ce: 591/592, 99%, 0.0/s, elapsed: 00:23:01
# [31m /usr/share/foreman/script/foreman-rake config      -k ssl_ca_file -v '/etc/foreman/proxy_ca.pem'      -k ssl_certificate -v '/etc/foreman/client_cert.pem'      -k ssl_priv_key -v '/etc/foreman/client_key.pem' returned 1 instead of one of [0]
# [0m[31m /Stage[main]/Certs::Foreman/Exec[foreman_certs_config]/returns: change from notrun to 0 failed: /usr/share/foreman/script/foreman-rake config      -k ssl_ca_file -v '/etc/foreman/proxy_ca.pem'      -k ssl_certificate -v '/etc/foreman/client_cert.pem'      -k ssl_priv_key -v '/etc/foreman/client_key.pem' returned 1 instead of one of [0]
# [0m[31m Could not set 'present' on ensure: 422 Unprocessable Entity at 12:/vagrant/katello-installer/modules/foreman_proxy/manifests/register.pp
# [0mError: Could not set 'present' on ensure: 422 Unpr: 591/592, 99%, 0.0/s, elapsed: 00:24:43
# [31m Could not set 'present' on ensure: 422 Unprocessable Entity at 12:/vagrant/katello-installer/modules/foreman_proxy/manifests/register.pp
# [0m[31m /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[katello-centos6-bats.example.com]/ensure: change from absent to present failed: Could not set 'present' on ensure: 422 Unprocessable Entity at 12:/vagrant/katello-installer/modules/foreman_proxy/manifests/register.pp
# [0m[31m /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[katello-centos6-bats.example.com]: Failed to call refresh: missing param 'id' in parameters
# [0m[31m /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[katello-centos6-bats.example.com]: missing param 'id' in parameters
# [0mDebug: Processing report from katello-centos6-bats: 591/592, 99%, 0.0/s, elapsed: 00:24:44
# [32mDone                                              [0m: 592/592, 100%, 0.0/s, elapsed: 00:24:51
# [32mDone                                              [0m: 592/592, 100%, 0.0/s, elapsed: 00:24:51
#   [1m[31mSomething went wrong![0m Check the log for ERROR-level output
#   The full log is at [1m[36m/var/log/katello-installer/katello-installer.log[0m
#   [1m[31mSomething went wrong![0m Check the log for ERROR-level output
#   The full log is at [1m[36m/var/log/katello-installer/katello-installer.log[0m
not ok 5 run the installer once again
# (in test file fb-install-katello.bats, line 73)
#   `./bin/katello-installer --no-colors -v' failed with status 6
# tput: No value for $TERM and no -T specified
```

**Comment by dustints** [comment]
production.log
``` 
  Rendered api/v2/errors/unprocessable_entity.json.rabl within api/v2/layouts/error_layout (2.3ms)
Completed 422 Unprocessable Entity in 240ms (Views: 5.7ms | ActiveRecord: 4.8ms)
Processing by Api::V2::SmartProxiesController#index as JSON
  Parameters: {"search"=>"name=katello-centos6-bats.example.com", "apiv"=>"v2", "smart_proxy"=>{}}
Authorized user foreman_api_admin(API Admin)
  Rendered api/v2/smart_proxies/index.json.rabl within api/v2/layouts/index_layout (9.2ms)
Completed 200 OK in 41ms (Views: 20.2ms | ActiveRecord: 3.5ms)
Connecting to database specified by database.yml
ENCRYPTION_KEY is not defined, so encryption is turned off for ComputeResource.
Creating scope :completer_scope. Overwriting existing method Location.completer_scope.
Creating scope :completer_scope. Overwriting existing method Organization.completer_scope.
Client connected.
Connected to server.
Client disconnected.
Processing by Api::V2::SmartProxiesController#index as JSON
  Parameters: {"search"=>"name=katello-centos6-bats.example.com", "apiv"=>"v2", "smart_proxy"=>{}}
Authorized user foreman_api_admin(API Admin)
  Rendered api/v2/smart_proxies/index.json.rabl within api/v2/layouts/index_layout (5.9ms)
Completed 200 OK in 69ms (Views: 14.9ms | ActiveRecord: 5.9ms)
Processing by Api::V2::SmartProxiesController#create as JSON
  Parameters: {"smart_proxy"=>{"url"=>"https://katello-centos6-bats.example.com:9090", "name"=>"katello-centos6-bats.example.com"}, "apiv"=>"v2"}
Authorized user foreman_api_admin(API Admin)
Unprocessable entity SmartProxy (id: new):
  Unable to communicate with the proxy: ERF12-2530 [ProxyAPI::ProxyException]: Unable to detect features ([OpenSSL::SSL::SSLError]: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verif...) for proxy http»
  Please check the proxy is configured and running on the host.

  Rendered api/v2/errors/unprocessable_entity.json.rabl within api/v2/layouts/error_layout (1.5ms)
Completed 422 Unprocessable Entity in 51ms (Views: 2.9ms | ActiveRecord: 4.3ms)
Processing by UsersController#login as */*
  Rendered users/login.html.erb within layouts/login (6.7ms)
  Rendered layouts/base.html.erb (3.6ms)
Completed 200 OK in 56ms (Views: 44.9ms | ActiveRecord: 0.7ms)
Processing by Api::V2::HostsController#facts as JSON
  Parameters: {"certname"=>"katello-centos6-bats.example.com", "name"=>"katello-centos6-bats.example.com", "facts"=>"[FILTERED]", "apiv"=>"v2", :host=>{"name"=>"katello-centos6-bats.example.com", "certname"=>"katello-centos6-bats.example.»
No smart proxy server found on ["katello-centos6-bats.example.com"] and is not in trusted_puppetmaster_hosts
  Rendered api/v2/errors/access_denied.json.rabl within api/v2/layouts/error_layout (1.7ms)
Filter chain halted as #<Proc:0x000000071c05a0@/usr/share/foreman/app/controllers/concerns/foreman/controller/smart_proxy_auth.rb:15> rendered or redirected
Completed 403 Forbidden in 72ms (Views: 37.0ms | ActiveRecord: 3.8ms)
Processing by HostsController#externalNodes as YML
  Parameters: {"name"=>"katello-centos6-bats.example.com"}
No smart proxy server found on ["katello-centos6-bats.example.com"] and is not in trusted_puppetmaster_hosts
Redirected to https://katello-centos6-bats.example.com/users/login
Filter chain halted as #<Proc:0x00000007d0ff00@/usr/share/foreman/app/controllers/concerns/foreman/controller/smart_proxy_auth.rb:15> rendered or redirected
Completed 403 Forbidden in 21ms (ActiveRecord: 0.9ms)
Processing by Api::V2::ReportsController#create as JSON
  Parameters: {"report"=>"[FILTERED]", "apiv"=>"v2"}
No smart proxy server found on ["katello-centos6-bats.example.com"] and is not in trusted_puppetmaster_hosts
  Rendered api/v2/errors/access_denied.json.rabl within api/v2/layouts/error_layout (1.0ms)
Filter chain halted as #<Proc:0x00000009e9f418@/usr/share/foreman/app/controllers/concerns/foreman/controller/smart_proxy_auth.rb:15> rendered or redirected
Completed 403 Forbidden in 18ms (Views: 3.5ms | ActiveRecord: 1.0ms)
```

**Comment by dustints** [comment]
config task is not loading right...
invalid option -k
Options are ...
    -C, --classic-namespace          Put Task and FileTask in the top level namespace
    -D, --describe [PATTERN]         Describe the tasks (matching optional PATTERN), then exit.
    -n, --dry-run                    Do a dry run without executing actions.
    -e, --execute CODE               Execute some Ruby code and exit.
    -p, --execute-print CODE         Execute some Ruby code, print the result, then exit.
    -E, --execute-continue CODE      Execute some Ruby code, then continue with normal task processing.
    -I, --libdir LIBDIR              Include LIBDIR in the search path for required modules.
    -N, --no-search, --nosearch      Do not search parent directories for the Rakefile.
    -P, --prereqs                    Display the tasks and dependencies, then exit.
    -q, --quiet                      Do not log messages to standard output.
    -f, --rakefile [FILE]            Use FILE as the rakefile.
    -R, --rakelibdir RAKELIBDIR,     Auto-import any .rake files in RAKELIBDIR. (default is 'rakelib')
        --rakelib
    -r, --require MODULE             Require MODULE before executing rakefile.
        --rules                      Trace the rules resolution.
    -s, --silent                     Like --quiet, but also suppresses the 'in directory' announcement.
    -g, --system                     Using system wide (global) rakefiles (usually '~/.rake/*.rake').
    -G, --no-system, --nosystem      Use standard project Rakefile search paths, ignore system wide rakefiles.
    -T, --tasks [PATTERN]            Display the tasks (matching optional PATTERN) with descriptions, then exit.
    -t, --trace                      Turn on invoke/execute tracing, enable full backtrace.
    -v, --verbose                    Log message to standard output.
    -V, --version                    Display the program version.
    -W, --where [PATTERN]            Describe the tasks (matching optional PATTERN), then exit.
    -X, --no-deprecation-warnings    Disable the deprecation warnings.
    -h, -H, --help                   Display this help message.

**Comment by stbenjam** [comment]
@dustints https://github.com/Katello/puppet-certs/pull/52

**Comment by dustints** [comment]
fix fix in http://github.com/Katello/puppet-certs/pull/52

**Comment by ehelms** [comment]
ACK

**Pull request merged**
