### PR TITLE
Fixes #10350: Set qdrouterd certs permission to qdrouterd user

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
What about https://github.com/Katello/puppet-qpid/blob/master/manifests/router/config.pp#L28?

**Comment by stbenjam** [comment]
Also, this will fail if the new packages aren't already in our repos - the `qdrotuerd` user doesn't exist on the packages that are out there in the wild now.

**Comment by ehelms** [comment]
@stbenjam I found no difference for the config file ownership testing this out locally.

**Comment by ehelms** [comment]
I should note I was testing against packages that have this error, so changing the crt/key ownership fixed them for me.

**Comment by stbenjam** [comment]
Ah ok, well APJ

**Pull request merged**
