### PR TITLE
Fixes #23292 - make s390x ks repos bootable

### PR DESCRIPTION
**Pull request by sean797**

### CODE REVIEW

**Comment by sean797** [comment]
Thanks, rebased

**Comment by sean797** [comment]
@jlsherrill that wasn't the case on the most recent discussion. 
https://community.theforeman.org/t/database-and-service-actions-in-rpm-post-scripts/7311/6

My understanding of the outcome:
- Some users want migrations run in `%postrans`
- Some users DO NOT want migrations run in `%postrans` (Foreman clusters would be one use-case)
- Lets extracts it out to another script (maybe foreman-maintain?) and `%postrans` can call the script
- The script can actaully run migrations (or not) based on user configuration

**Comment by ekohl** [comment]
@jlsherrill my thoughts about core was a `foreman-rake upgrade` which plugins could extend. It would be similar to the model we have here in the installer and plugins could add tasks into it. Idempotency is an important one. Then we can call it either in `%posttrans` (possibly guarded with a setting), `foreman-installer`, `foreman-maintain` or a containerization tool.

**Comment by jlsherrill** [comment]
ah i see, i must have been thinking about a past conversation.  I think that plan sounds good.  I'm hoping that our team can tackle this work very soon

**Comment by ehelms** [comment]
@sean797 Mind doing a rebase?

**Comment by sean797** [comment]
rebased :+1:

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
