### PR TITLE
fixes #18068 - ensure pulp is available during puppet upgrade

### PR DESCRIPTION
**Pull request by Klaas-**
puppet-agent-oauth needs to be installed before stopping services

### CODE REVIEW

**Comment by stbenjam** [comment]
In the Katello upgrades we solve this kind of problem by just starting `httpd` before we run the upgrade - so pulp is available.  I wonder if that would work here instead? 

It may not work, since we remove the puppet-server package but the httpd is probably still configured for the Ruby puppet master via  Passenger.

**Comment by Klaas-** [comment]
@stbenjam I did not try that, I only noticed the missing package leads to errors and you guys already have the same functionality for puppet-agent and puppetserver packages :)

**Comment by Klaas-** [comment]
@beav wrote the code for the puppet-upgrade -- maybe he can tell us more :)

**Comment by beav** [comment]
I'm 👍 for starting httpd before upgrading to make the packages available. That way we don't have to find the packages to install one by one via trial and error

**Comment by Klaas-** [comment]
okay, so you want to close this pr and fix it yourself or do you want to merge this one and remove it once you've finished and tested if httpd starting during puppet-upgrade is working?

**Comment by Klaas-** [comment]
@beav @stbenjam how are we going to move on with this bug?

**Comment by stbenjam** [comment]
The best solution would be to update this PR to start httpd instead and we can help you test it.

**Comment by Klaas-** [comment]
@stbenjam done, its untested as of now - I already deleted the snapshots of my update test vms

**Comment by chris1984** [comment]
@Klaas-  do you have steps to test this? I want to do a test here.

**Comment by Klaas-** [comment]
@chris1984 I upgrade from katello 3.1.* (puppet3) to katello 3.2.3 and after the upgrade I upgraded puppet -- just like the docs suggest.

I will have another system to test once I've finished the acceptance testing of katello 3.2.3, but I can't give an eta for that

**Comment by Klaas-** [comment]
okay I changed some more things to get httpd working - I tested this revision and it seems to work

**Comment by jlsherrill** [comment]
@stbenjam you okay with this?

**Comment by stbenjam** [comment]
Thanks everyone!

**Pull request merged**
