### PR TITLE
Fixes #9888 - require openssl for katello-installer-base

### PR DESCRIPTION
**Pull request by dustints**
openssl is needed for katello-certs-check

### CODE REVIEW

**Comment by ehelms** [comment]
Couple of things:

1) We should update https://github.com/Katello/katello-installer/blob/0c126a368f2e37755aa0d2fada2c54f51ea33f09/modules/certs/manifests/init.pp#L123 to use `random_password` like we do elsewhere and remove dependency on puppet-common if we can
2) puppet-certs relies on katello-certs-tools which handles the openssl requires for us, however, the `generate_password` function is getting called prior to the `certs::install` which would properly ensure katello-certs-tools is installed (and thus openssl).
3) We should be requiring openssl only because of https://github.com/Katello/katello-installer/blob/master/bin/katello-certs-check which relies on it.

**Comment by dustints** [comment]
@ehelms 
>>  1)
created https://github.com/Katello/puppet-certs/pull/57

**Comment by dustints** [comment]
updated commit message

**Comment by dustints** [comment]
updated, added commit for puppet-certs update

**Comment by ehelms** [comment]
Can squash commits please?

**Comment by dustints** [comment]
squashed

**Comment by ehelms** [comment]
APJ

**Comment by dustints** [comment]
seeing 
```
./bin/katello-installer --foreman-admin-password=changeme
# tput: No value for $TERM and no -T specified
# /usr/lib/ruby/site_ruby/1.8/puppet/context.rb:54:in `lookup': Could not parse for environment production: no 'environments' in {:current_environment=>#<Puppet::Node::Environment:0x7f5112c1e5c0 @modulepath=[], @watching=true, @name=:"*root*", @config_version=nil, @manifest=:no_manifest>, :root_environment=>#<Puppet::Node::Environment:0x7f5112c1e5c0 @modulepath=[], @watching=true, @name=:"*root*", @config_version=nil, @manifest=:no_manifest>} at top of [[0, nil, nil]] (Puppet::Error)
# 	from /usr/lib/ruby/site_ruby/1.8/puppet.rb:236:in `lookup'
# 	from /usr/lib/ruby/site_ruby/1.8/puppet.rb:264:in `future_parser?'
# 	from /usr/lib/ruby/site_ruby/1.8/puppet/parser/parser_factory.rb:12:in `parser'
# 	from /usr/lib/ruby/site_ruby/1.8/puppet/node/environment.rb:541:in `perform_initial_import'
# 	from /usr/lib/ruby/site_ruby/1.8/puppet/node/environment.rb:276:in `known_resource_types'
# 	from /usr/lib/ruby/site_ruby/1.8/puppet/resource/type_collection_helper.rb:5:in `known_resource_types'
# 	from /usr/lib/ruby/site_ruby/1.8/puppet/parser/parser_support.rb:120:in `import'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo_parsers-0.0.4/lib/kafo_parsers/puppet_module_parser.rb:38:in `initialize'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo_parsers-0.0.4/lib/kafo_parsers/puppet_module_parser.rb:16:in `new'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo_parsers-0.0.4/lib/kafo_parsers/puppet_module_parser.rb:16:in `parse'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/puppet_module.rb:44:in `parse'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/configuration.rb:85:in `modules'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/configuration.rb:85:in `map'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/configuration.rb:85:in `modules'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/kafo_configure.rb:172:in `modules'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/kafo_configure.rb:154:in `params'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/kafo_configure.rb:187:in `set_parameters'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/kafo_configure.rb:66:in `initialize'
# 	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `new'
# 	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `run'
# 	from /usr/lib/ruby/gems/1.8/gems/kafo-0.6.6/lib/kafo/kafo_configure.rb:118:in `run'
# 	from ./bin/katello-installer:9
not ok 5 run the installer once again
```

**Comment by ehelms** [comment]
[test]

**Pull request merged**
