### PR TITLE
refs #8175, #7064 - isolate consumer actions, and use foreman_proxy fork

### PR DESCRIPTION
**Pull request by stbenjam**
This commit pulls in the changes needed to isolate consumer actions, as
well as pinning theforeman-foreman_proxy to our fork, which will avoid
pulling in a new puppetlabs-apache.  :cry: 

This avoids #7064, the case where the installer segfaults due to poor garbage collection in 1.8.7.

### CODE REVIEW

**Comment by stbenjam** [comment]
Before merging we need:
  - [ ] python-gofer 2.5.3
  - [ ] dispatch router packages in our repos
  - [ ] https://github.com/Katello/katello-agent/pull/17
  - [ ] https://github.com/Katello/katello-agent/pull/18

**Comment by stbenjam** [comment]
[test]

**Comment by stbenjam** [comment]
[test]

**Comment by iNecas** [comment]
ACK

**Pull request merged**
