### PR TITLE
3.5.0 rc2 cherry picks

### PR DESCRIPTION
**Pull request by akofink**

### CODE REVIEW

**Comment by ekohl** [comment]
Rubocop is not happy :(

**Comment by akofink** [comment]
Seeing as these are cherry picks, doesn't that mean we merged some PRs in this repo that also failed rubocop?

**Comment by ekohl** [comment]
https://github.com/Katello/katello-installer/commit/bf2d495c43513f18af41d89062e7386a936ceddd does fix some rubocop errors.

**Comment by akofink** [comment]
Updated with bf2d495

**Comment by ekohl** [comment]
Still trailing whitespace somewhere :(

**Comment by akofink** [comment]
Easy enough to fix. Updated.

**Comment by akofink** [comment]
Ok, so rubocop is happy, but we have a dependency issue with camptocamp-systemd

**Comment by ekohl** [comment]
I'll look at doing new releases which include https://github.com/Katello/puppet-qpid/commit/157afe2c131fd2791a5f361c05f100fd1a28a90e

**Comment by ekohl** [comment]
Thoughts on including a0a897dd62b5e0b57f105d073569b66a21564fe4?

**Comment by akofink** [comment]
@ekohl Fine with me. I do wonder if you should associate an issue with that commit.

**Comment by ekohl** [comment]
@akofink it appears @theforeman-bot does think that ;)

**Comment by akofink** [comment]
Updated with a0a897d

**Comment by ekohl** [comment]
https://github.com/ekohl/katello-installer/commit/44ad703ce343e4b19f8ad88bd117e3f4dc2b8838 should resolve the build issue with systemd and extlib.

**Comment by ekohl** [comment]
e169f45641d16a5c84daebed86157bb9a74d9172 should fix the build.

**Comment by akofink** [comment]
Updated

**Pull request merged**
