### PR TITLE
Fixes #15511 - fix setup_local to copy to correct dir

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
without this, when running the rake task it put the moduels in ./modules/modules/ which didn't seem correct, unless I'm just doing it wrong

**Comment by stbenjam** [comment]
Ah that makes sense if the modules directory already exists, but what if the modules directory isn't empty like when someone ran librarian manually? Maybe it might make sense to delete the local modules directory, too, before the cp_r.

**Comment by jlsherrill** [comment]
ahhh!  that makes sense.  I will update to do that

**Comment by stbenjam** [comment]
Looks ok to me, ACK

**Pull request merged**
